# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zmqVOExrPn97aWWwTEnfZokPTqmjaUyT
"""

"""
calibrate_sensors.py

Reproducible, automatable calibration for smartphone IMU & magnetometer.
- Estimates accel & gyro biases from stationary segments
- Full 3D ellipsoid fit for magnetometer (hard-iron + soft-iron)
- Optional Allan deviation for gyro (bias instability reporting)
- Exports JSON params + calibrated CSV

Usage:
  python calibrate_sensors.py \
      --input Whole_Bump_Pothole_Uncalibrated.csv \
      --output Whole_Bump_Pothole_Calibrated.csv \
      --params calibration_params.json \
      --compute_allan

Notes:
- If your CSV has a timestamp column, pass --timecol name (optional).
- Stationary detection uses rolling std; adjust thresholds if needed.
"""

import json
import argparse
import numpy as np
import pandas as pd

from dataclasses import dataclass, asdict

# Optional: for ellipsoid fit & Allan deviation
from numpy.linalg import lstsq, inv, eig
from scipy.signal import medfilt
from scipy.ndimage import uniform_filter1d

# --------------------------
# Utilities & Data Classes
# --------------------------

@dataclass
class AccelGyroCal:
    accel_bias: list  # [bx, by, bz]
    gyro_bias: list   # [bx, by, bz]

@dataclass
class MagCal:
    offset: list      # hard-iron [ox, oy, oz]
    transform: list   # 3x3 soft-iron correction matrix row-major

@dataclass
class CalibrationParams:
    accel_gyro: AccelGyroCal
    magnetometer: MagCal
    sampling_hz_estimate: float | None = None
    notes: str = "Bias from stationary segments; magnetometer via ellipsoid fit."

# --------------------------
# Stationary Detection
# --------------------------

def estimate_sampling_rate(df, timecol=None):
    if timecol is None or timecol not in df.columns:
        return None
    t = pd.to_datetime(df[timecol], errors="coerce")
    if t.isna().all():
        # maybe numeric seconds
        t = pd.to_numeric(df[timecol], errors="coerce")
        if t.isna().all():
            return None
        dt = np.diff(t.values)
        dt = dt[~np.isnan(dt)]
        if len(dt) == 0: return None
        hz = 1.0 / np.median(dt)
        return float(hz)
    dt = (t.astype("int64").to_numpy() / 1e9)
    dt = np.diff(dt)
    dt = dt[~np.isnan(dt)]
    if len(dt) == 0: return None
    hz = 1.0 / np.median(dt)
    return float(hz)

def find_stationary_mask(df, accel_cols, gyro_cols, win_samples=180,
                         accel_std_th=0.02, gyro_std_th=0.01):
    """
    Heuristic: stationary when rolling std of accel & gyro are small.
    - accel_std_th in normalized units (m/s^2); adjust if raw scale differs.
    - gyro_std_th in rad/s.
    """
    acc = df[accel_cols].to_numpy()
    gyr = df[gyro_cols].to_numpy()

    # Robustify with median filter
    acc_f = medfilt(acc, kernel_size=(5,1))
    gyr_f = medfilt(gyr, kernel_size=(5,1))

    # Rolling std via uniform filter (approx)
    def rolling_std(x, w):
        mu = uniform_filter1d(x, size=w, mode="nearest", axis=0)
        mu2 = uniform_filter1d(x**2, size=w, mode="nearest", axis=0)
        var = np.clip(mu2 - mu**2, a_min=0, a_max=None)
        return np.sqrt(var)

    acc_std = rolling_std(acc_f, win_samples)
    gyr_std = rolling_std(gyr_f, win_samples)

    acc_ok = (np.max(acc_std, axis=1) < accel_std_th)
    gyr_ok = (np.max(gyr_std, axis=1) < gyro_std_th)
    return acc_ok & gyr_ok

def estimate_bias_from_stationary(df, cols, stationary_mask):
    if not np.any(stationary_mask):
        # fallback to global mean (warn user)
        return df[cols].mean().to_numpy()
    return df.loc[stationary_mask, cols].mean().to_numpy()

# --------------------------
# Magnetometer Ellipsoid Fit
# --------------------------

def fit_magnetometer_ellipsoid(mag):
    """
    Fit ellipsoid: x^T A x + b^T x + c = 0
    Return hard-iron offset 'center' and soft-iron correction matrix 'T'
    such that m_cal = T @ (m_raw - center)
    Reference approach: least squares quadratic fit + eigen-decomposition.
    """
    x = mag[:,0]; y = mag[:,1]; z = mag[:,2]
    D = np.column_stack([x*x, y*y, z*z, 2*x*y, 2*x*z, 2*y*z, 2*x, 2*y, 2*z, np.ones_like(x)])
    # Solve D*p = 0 subject to ||p||=1 -> use SVD or least squares with constraint.
    # Practical approach: minimize ||D p|| with smallest singular vector:
    u, s, vh = np.linalg.svd(D, full_matrices=False)
    p = vh[-1, :]

    A = np.array([[p[0], p[3], p[4]],
                  [p[3], p[1], p[5]],
                  [p[4], p[5], p[2]]], dtype=float)
    b = np.array([p[6], p[7], p[8]], dtype=float)
    c = p[9]

    # Center (hard-iron) = -0.5 * A^{-1} b
    center = -0.5 * inv(A) @ b

    # Translate to center to get shape matrix
    # Ellipsoid equation -> (x - center)^T A (x - center) = k
    k = center.T @ A @ center - c

    # Soft-iron: find transform T s.t. T^T T = A / k  -> Cholesky of (A/k)
    A_norm = A / k
    # Ensure symmetric positive definite (numerical guard)
    A_sym = 0.5 * (A_norm + A_norm.T)
    eigvals, eigvecs = eig(A_sym)
    # Build whitening transform: T = diag(1/sqrt(eigvals)) @ eigvecs^T
    # We want T such that T @ (m - center) becomes spherical.
    D_inv_sqrt = np.diag(1.0 / np.sqrt(np.real(eigvals)))
    T = D_inv_sqrt @ np.real(eigvecs).T
    return np.real(center), T

# --------------------------
# Allan Deviation (Optional)
# --------------------------

def allan_deviation(omega, fs, taus=None):
    """
    Simple overlapping Allan deviation for 1D series (gyro component).
    Returns tau (s) and sigma (units of omega).
    """
    if taus is None:
        # Log-spaced integration times from ~1/fs to ~len/10
        max_m = max(2, len(omega)//10)
        m_vals = np.unique((np.logspace(0, np.log10(max_m), num=30)).astype(int))
    else:
        m_vals = np.unique((np.array(taus)*fs).astype(int))
    omega = np.asarray(omega, dtype=float)
    y = np.cumsum(omega) / fs  # integrate to angle
    sigmas = []
    taus_out = []
    for m in m_vals:
        if m < 1 or 2*m >= len(y):
            continue
        # overlapping
        diff = y[2*m:] - 2*y[m:-m] + y[:-2*m]
        sigma2 = 0.5 * np.mean(diff**2) / (m/fs)**2
        sigmas.append(np.sqrt(sigma2))
        taus_out.append(m/fs)
    return np.array(taus_out), np.array(sigmas)

# --------------------------
# Main Calibration Pipeline
# --------------------------

def run_calibration(input_csv, output_csv, params_json, timecol=None, compute_allan=False):
    df = pd.read_csv(input_csv)

    accel_cols_u = ['accelerometer_uncalibrated_x','accelerometer_uncalibrated_y','accelerometer_uncalibrated_z']
    gyro_cols_u  = ['gyroscope_uncalibrated_x','gyroscope_uncalibrated_y','gyroscope_uncalibrated_z']
    mag_cols_u   = ['magnetometer_uncalibrated_x','magnetometer_uncalibrated_y','magnetometer_uncalibrated_z']

    # Sanity: check columns exist
    for cols in (accel_cols_u, gyro_cols_u, mag_cols_u):
        for c in cols:
            if c not in df.columns:
                raise ValueError(f"Required column missing: {c}")

    # Estimate sampling rate if possible (only for reporting/Allan)
    fs = estimate_sampling_rate(df, timecol=timecol)

    # Heuristic window length ~2 seconds if fs known, else 180 (~2s @ 90Hz)
    win = int(2*fs) if (fs is not None) else 180

    # Stationary detection
    stationary = find_stationary_mask(
        df, accel_cols=accel_cols_u, gyro_cols=gyro_cols_u,
        win_samples=max(30, win), accel_std_th=0.05, gyro_std_th=0.01
    )

    # Bias estimation
    accel_bias = estimate_bias_from_stationary(df, accel_cols_u, stationary)
    gyro_bias  = estimate_bias_from_stationary(df, gyro_cols_u,  stationary)

    # Magnetometer ellipsoid fit (use whole file for robust fit)
    mag_raw = df[mag_cols_u].to_numpy()
    mag_center, mag_T = fit_magnetometer_ellipsoid(mag_raw)

    # Apply calibration
    acc_u = df[accel_cols_u].to_numpy()
    gyr_u = df[gyro_cols_u].to_numpy()
    mag_u = df[mag_cols_u].to_numpy()

    acc_c = acc_u - accel_bias
    gyr_c = gyr_u - gyro_bias
    mag_c = (mag_T @ (mag_u - mag_center).T).T  # (N,3)

    # Write calibrated columns
    df['accelerometer_calibrated_x'] = acc_c[:,0]
    df['accelerometer_calibrated_y'] = acc_c[:,1]
    df['accelerometer_calibrated_z'] = acc_c[:,2]

    df['gyroscope_calibrated_x'] = gyr_c[:,0]
    df['gyroscope_calibrated_y'] = gyr_c[:,1]
    df['gyroscope_calibrated_z'] = gyr_c[:,2]

    df['magnetometer_calibrated_x'] = mag_c[:,0]
    df['magnetometer_calibrated_y'] = mag_c[:,1]
    df['magnetometer_calibrated_z'] = mag_c[:,2]

    # Save calibrated CSV
    df.to_csv(output_csv, index=False)

    # Save params JSON
    params = CalibrationParams(
        accel_gyro=AccelGyroCal(
            accel_bias=accel_bias.tolist(),
            gyro_bias=gyro_bias.tolist()
        ),
        magnetometer=MagCal(
            offset=mag_center.tolist(),
            transform=mag_T.tolist()
        ),
        sampling_hz_estimate=fs
    )
    with open(params_json, "w") as f:
        json.dump(asdict(params), f, indent=2)

    # Optional: Allan deviation for reporting
    allan_report = {}
    if compute_allan and fs is not None:
        for i, ax in enumerate(['x','y','z']):
            tau, sigma = allan_deviation(gyr_u[:,i] - gyro_bias[i], fs=fs)
            allan_report[f'gyro_{ax}'] = {
                "tau_s": tau.tolist(),
                "allan_deviation": sigma.tolist()
            }
        # Append to params JSON
        with open(params_json, "r") as f:
            blob = json.load(f)
        blob["gyro_allan_deviation"] = allan_report
        with open(params_json, "w") as f:
            json.dump(blob, f, indent=2)

    # Console summary (pasteable into manuscript)
    print("\n=== Calibration Summary ===")
    print(f"Estimated sampling rate (Hz): {fs if fs else 'N/A'}")
    print(f"Stationary samples used: {int(stationary.sum())} / {len(stationary)}")
    print(f"Accel bias [x,y,z]: {accel_bias}")
    print(f"Gyro  bias [x,y,z]: {gyro_bias}")
    print(f"Mag hard-iron offset [x,y,z]: {mag_center}")
    print("Mag soft-iron transform (row-major):")
    print(mag_T)
    if compute_allan and fs is not None:
        print("Allan deviation curves saved in JSON (gyro_allan_deviation).")
    print(f"\nSaved calibrated CSV: {output_csv}")
    print(f"Saved calibration params: {params_json}")

# --------------------------
# CLI
# --------------------------

def parse_args():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True, help="Path to uncalibrated CSV")
    ap.add_argument("--output", required=True, help="Path to calibrated CSV output")
    ap.add_argument("--params", required=True, help="Path to write calibration_params.json")
    ap.add_argument("--timecol", default=None, help="Optional name of timestamp column")
    ap.add_argument("--compute_allan", action="store_true", help="Compute Allan deviation for gyro")
    return ap.parse_args()

if __name__ == "__main__":
    args = parse_args()
    run_calibration(args.input, args.output, args.params,
                    timecol=args.timecol, compute_allan=args.compute_allan)